name: update dependencies
on:

  schedule:
    - cron:  '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: development
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: lts/iron
      - name: update
        run: yarn install && yarn upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          base: development
          branch: dependency-updates
          delete-branch: true
          title: Dependency Updates
          commit-message: Dependency updates
